In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [7]:
## sentences

sentence=[
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good',
]

In [8]:
# Define the vocabulary size

vocabulary_size=10000


In [19]:
## one hot representation

one_hot_repr=[one_hot(i, vocabulary_size)for i in sentence]
one_hot_repr

[[7746, 7784, 5933, 2129],
 [7746, 7784, 5933, 5943],
 [7746, 4955, 5933, 8453],
 [8802, 2136, 4845, 5663, 4440],
 [8802, 2136, 4845, 5663, 9929],
 [7565, 7746, 2864, 5933, 1305],
 [3543, 8887, 7253, 5663]]

In [25]:
# Wordd Embedding Representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [26]:
import numpy as np

In [31]:
# pad sequences used for suppose if we have 5 words and we convert it into 8 that use padding to make equal through
# pre=means before and post means after

sent_length=8  # we custom max length because in our dataset it have 5 max lenwords
embedded_docs = pad_sequences(one_hot_repr, padding='pre', maxlen=sent_length)
print(embedded_docs)


[[   0    0    0    0 7746 7784 5933 2129]
 [   0    0    0    0 7746 7784 5933 5943]
 [   0    0    0    0 7746 4955 5933 8453]
 [   0    0    0 8802 2136 4845 5663 4440]
 [   0    0    0 8802 2136 4845 5663 9929]
 [   0    0    0 7565 7746 2864 5933 1305]
 [   0    0    0    0 3543 8887 7253 5663]]


In [32]:
### feature representation

dim=10

In [33]:
model=Sequential()
model.add(Embedding(vocabulary_size, dim, input_length=sent_length))
model.compile('adam', 'mse')

In [34]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [35]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 108ms/step


array([[[ 0.02263344, -0.02616184,  0.02387145,  0.04889962,
          0.04294088,  0.04580997,  0.00538535,  0.04914293,
          0.02590675, -0.02476606],
        [ 0.02263344, -0.02616184,  0.02387145,  0.04889962,
          0.04294088,  0.04580997,  0.00538535,  0.04914293,
          0.02590675, -0.02476606],
        [ 0.02263344, -0.02616184,  0.02387145,  0.04889962,
          0.04294088,  0.04580997,  0.00538535,  0.04914293,
          0.02590675, -0.02476606],
        [ 0.02263344, -0.02616184,  0.02387145,  0.04889962,
          0.04294088,  0.04580997,  0.00538535,  0.04914293,
          0.02590675, -0.02476606],
        [-0.00251659, -0.03594974,  0.03438563,  0.02937782,
         -0.0006895 , -0.0016314 , -0.04023562, -0.02407232,
          0.01544741, -0.015161  ],
        [ 0.01485178, -0.04266349,  0.02954075,  0.0208827 ,
         -0.03767377,  0.00114639, -0.04187154, -0.04759192,
         -0.0136498 ,  0.02721569],
        [-0.04777203, -0.03459463, -0.00493493, -0.0

In [36]:
embedded_docs[0]

array([   0,    0,    0,    0, 7746, 7784, 5933, 2129], dtype=int32)

In [42]:
model.predict(embedded_docs[0])


1/1 [==============================] - 0s 18ms/step


array([[ 0.02263344, -0.02616184,  0.02387145,  0.04889962,  0.04294088,
         0.04580997,  0.00538535,  0.04914293,  0.02590675, -0.02476606],
       [ 0.02263344, -0.02616184,  0.02387145,  0.04889962,  0.04294088,
         0.04580997,  0.00538535,  0.04914293,  0.02590675, -0.02476606],
       [ 0.02263344, -0.02616184,  0.02387145,  0.04889962,  0.04294088,
         0.04580997,  0.00538535,  0.04914293,  0.02590675, -0.02476606],
       [ 0.02263344, -0.02616184,  0.02387145,  0.04889962,  0.04294088,
         0.04580997,  0.00538535,  0.04914293,  0.02590675, -0.02476606],
       [-0.00251659, -0.03594974,  0.03438563,  0.02937782, -0.0006895 ,
        -0.0016314 , -0.04023562, -0.02407232,  0.01544741, -0.015161  ],
       [ 0.01485178, -0.04266349,  0.02954075,  0.0208827 , -0.03767377,
         0.00114639, -0.04187154, -0.04759192, -0.0136498 ,  0.02721569],
       [-0.04777203, -0.03459463, -0.00493493, -0.01220419,  0.02695126,
        -0.02838924,  0.02593147,  0.04933764